// Generated by CoffeeScript 1.6.3
(function() {
  YUI().use('node-base', 'node-event-delegate', 'app-base', 'app-transitions', 'handelbars', 'menuplugin', function(Y) {
    var pageApp;
    pageApp = new Y.App({
      views: {
        home: {
          preserve: true
        },
        Projects: {
          parent: 'home'
        },
        Blogs: {
          parent: 'home'
        },
        Videos: {
          parent: 'home'
        },
        Members: {
          parent: 'home'
        }
      },
      transitions: true,
      container: '#pageContent',
      serverRouting: true
    });
    pageApp.route(' /Projects', function() {
      return Y.one('#pageContent').set('text', 'Project list');
    });
    pageApp.route('/Blogs', function() {
      return Y.one('#pageContent').set('text', 'Blogs');
    });
    pageApp.route('/Videos', function() {
      return Y.one('#pageContent').set('text', 'Videos');
    });
    pageApp.route('/Members', function() {
      return Y.one('#pageContent').set('text', 'Member section');
    });
    pageApp.route('/Forum', function() {
      return window.location = 'http://teamojam.com/forums/';
    });
    Y.menuplugin.render();
    return pageApp.render().dispatch();
  });

}).call(this);
