// Generated by CoffeeScript 1.6.3
(function() {
  YUI.add('menuplugin', function(Y) {
    var bindPhoneMenu, contentMenuAnimation, menuAnim, menuDisplay, menuLink, menuLinkAnim, menuTemplate, menuTemplateSource, revese, rollLink, setupMenu, startSideMenu, toggleContentMenu, toggleMenus, toggleSideMenu;
    menuDisplay = null;
    menuTemplateSource = null;
    menuTemplate = null;
    menuLink = Y.one('#menuLink');
    rollLink = Y.one('#rollLink');
    revese = false;
    setupMenu = function() {
      menuDisplay = {
        menu: [
          {
            title: 'Team Projects',
            image: '103-map-white.png',
            link: 'Projects',
            quantity: '1'
          }, {
            title: 'Team Blogs',
            image: '251-sword-white.png',
            link: 'Blogs',
            quantity: '2'
          }, {
            title: 'Team Members',
            image: '111-user.png',
            link: 'Members',
            quantity: '5'
          }, {
            title: 'Forum',
            image: '33-cabinet-white.png',
            link: 'Forum'
          }
        ]
      };
      menuTemplateSource = Y.one('#menu-template').getHTML();
      return menuTemplate = Y.Handlebars.compile(menuTemplateSource);
    };
    menuAnim = Y.one('#menu').plug(Y.Plugin.NodeFX, {
      from: {
        left: 0
      },
      to: {
        left: 250
      },
      easing: Y.Easing.easeOut,
      duration: 0.5
    });
    menuLinkAnim = Y.one('#menuLink').plug(Y.Plugin.NodeFX, {
      from: {
        left: 0
      },
      to: {
        left: 250
      },
      easing: Y.Easing.easeOut,
      duration: 0.5
    });
    contentMenuAnimation = Y.one('.hero').plug(Y.Plugin.NodeFX, {
      from: {
        left: 0
      },
      to: {
        left: 100
      },
      easing: Y.Easing.easeOut,
      duration: 0.5
    });
    toggleMenus = function(e) {
      menuLinkAnim.fx.set('reverse', !menuLinkAnim.fx.get('reverse'));
      return menuLinkAnim.fx.run();
    };
    startSideMenu = function(e) {
      menuAnim.fx.set('reverse', !menuAnim.fx.get('reverse'));
      return menuAnim.fx.run();
    };
    toggleContentMenu = function(e) {
      contentMenuAnimation.fx.set('reverse', !contentMenuAnimation.fx.get('reverse'));
      return contentMenuAnimation.fx.run();
    };
    toggleSideMenu = function(e) {
      toggleMenus(e);
      startSideMenu(e);
      return toggleContentMenu(e);
    };
    bindPhoneMenu = function() {
      return menuLink.on('click', toggleSideMenu);
    };
    return Y.menuplugin = {
      render: function() {
        var html;
        setupMenu();
        html = menuTemplate(menuDisplay);
        Y.one('#menu').setHTML(html);
        return bindPhoneMenu();
      }
    };
  }, '0.1.1', {
    requires: ['handlebars-base', 'handelbars-comiler', 'handlebars', 'node', 'anim']
  });

}).call(this);
