// Generated by CoffeeScript 1.6.3
(function() {
  YUI.add('menuplugin', function(Y) {
    var bindPhoneMenu, menuAnim, menuDisplay, menuLink, menuLinkAnim, menuTemplate, menuTemplateSource, rollLink, setupMenu, startSideMenu, toggleMenus, toggleRollMenu, toggleSideMenu;
    menuDisplay = null;
    menuTemplateSource = null;
    menuTemplate = null;
    menuLink = Y.one('#menuLink');
    rollLink = Y.one('#rollLink');
    setupMenu = function() {
      menuDisplay = {
        menu: [
          {
            title: 'Team Projects',
            image: '103-map-white.png',
            link: 'Projects',
            quantity: '1'
          }, {
            title: 'Team Blogs',
            image: '251-sword-white.png',
            link: 'Blogs',
            quantity: '2'
          }, {
            title: 'Team Videos',
            image: '43-film-roll.png',
            link: 'Videos',
            quantity: '0'
          }, {
            title: 'Team Members',
            image: '111-user.png',
            link: 'Members',
            quantity: '5'
          }
        ]
      };
      menuTemplateSource = Y.one('#menu-template').getHTML();
      return menuTemplate = Y.Handlebars.compile(menuTemplateSource);
    };
    menuAnim = Y.one('#menu').plug(Y.Plugin.NodeFX, {
      from: {
        left: 0
      },
      to: {
        left: 250
      },
      easing: Y.Easing.easeOut,
      duration: 0.5
    });
    menuLinkAnim = Y.one('#menuLink').plug(Y.Plugin.NodeFX, {
      from: {
        left: 0
      },
      to: {
        left: 250
      },
      easing: Y.Easing.easeOut,
      duration: 0.5
    });
    toggleMenus = function(e) {
      menuLinkAnim.fx.run();
      return menuLinkAnim.fx.set('reverse', !menuAnim.fx.get('reverse'));
    };
    startSideMenu = function(e) {
      menuAnim.fx.run();
      return menuAnim.fx.set('reverse', !menuAnim.fx.get('reverse'));
    };
    toggleSideMenu = function(e) {
      toggleMenus(e);
      return startSideMenu(e);
    };
    toggleRollMenu = function(e) {
      rollLinkAnim.fx.run();
      return rollLinkAnim.fx.set('reverse', !menuAnim.fx.get('reverse'));
    };
    bindPhoneMenu = function() {
      menuLink.on('click', toggleSideMenu);
      return rollLink.on('click', toggleRollMenu);
    };
    return Y.menuplugin = {
      render: function() {
        var html;
        setupMenu();
        html = menuTemplate(menuDisplay);
        Y.one('#menu').setHTML(html);
        return bindPhoneMenu();
      }
    };
  }, '0.1.1', {
    requires: ['handlebars-base', 'handelbars-comiler', 'handlebars', 'node', 'anim']
  });

}).call(this);
